/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.design;

import com.crud.CrudClient;
import com.crud.DonneesListeClient;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author Hyacinthe
 */
public class DesignClient extends javax.swing.JFrame {

    /**
     * Creates new form CLT_DESIGN
     */
    public DesignClient() {
        initComponents();
        affichageInstantanee();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRechercher = new javax.swing.JTextField();
        jLabelRechercher = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonAjouter = new javax.swing.JButton();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jButtonModifier = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        jButtonSupprimer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAffichageClient = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextFieldNom = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(20, 32767));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 60));
        jLabel7 = new javax.swing.JLabel();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextFieldPrenoms = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextFieldTelephone = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(20, 32767));
        jLabel9 = new javax.swing.JLabel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jTextFieldMail = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(40, 32767));
        jButton2 = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 220));
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(40, 32767));
        jButton1 = new javax.swing.JButton();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 40));
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(40, 32767));
        jButton4 = new javax.swing.JButton();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 40));
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(40, 32767));
        jButton3 = new javax.swing.JButton();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 150), new java.awt.Dimension(0, 150), new java.awt.Dimension(32767, 40));
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 172, 113));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 238, 233));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRÊT-TSIK");

        jTextFieldRechercher.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldRechercherInputMethodTextChanged(evt);
            }
        });
        jTextFieldRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechercherActionPerformed(evt);
            }
        });
        jTextFieldRechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRechercherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRechercherKeyReleased(evt);
            }
        });

        jLabelRechercher.setText("Rechercher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 646, Short.MAX_VALUE)
                .addComponent(jLabelRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 100));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Javanese Text", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 67, 94));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PAGE CLIENT");
        jLabel3.setAlignmentX(0.5F);
        jLabel3.setAlignmentY(0.14F);
        jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jButtonAjouter.setBackground(new java.awt.Color(15, 172, 113));
        jButtonAjouter.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jButtonAjouter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Ajout.png"))); // NOI18N
        jButtonAjouter.setText("AJOUTER");
        jButtonAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAjouter.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonAjouter);
        jPanel6.add(filler8);

        jButtonModifier.setBackground(new java.awt.Color(23, 150, 164));
        jButtonModifier.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jButtonModifier.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Modification.png"))); // NOI18N
        jButtonModifier.setText("MODIFIER");
        jButtonModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModifier.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonModifier);
        jPanel6.add(filler10);

        jButtonSupprimer.setBackground(new java.awt.Color(237, 67, 94));
        jButtonSupprimer.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jButtonSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/delete.png"))); // NOI18N
        jButtonSupprimer.setText("SUPPRIMER");
        jButtonSupprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSupprimer.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSupprimer);

        jLabel4.setFont(new java.awt.Font("Javanese Text", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(237, 67, 94));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LISTE DES CLIENTS");
        jLabel4.setAlignmentX(0.5F);
        jLabel4.setAlignmentY(0.14F);

        jTableAffichageClient.setAutoCreateRowSorter(true);
        jTableAffichageClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null},
                {null, "", null, null, null, null},
                {null, null, null, null, null, null},
                {null, "", null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NumCompte", "Nom", "Prenom", "Tel", "E-mail", "Budget"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableAffichageClient.setFocusTraversalPolicyProvider(true);
        jTableAffichageClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAffichageClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAffichageClient);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 13, 110));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOM :");
        jPanel7.add(jLabel5);
        jPanel7.add(filler11);

        jTextFieldNom.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextFieldNom.setForeground(new java.awt.Color(93, 13, 110));
        jTextFieldNom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 172, 113), 2));
        jTextFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomActionPerformed(evt);
            }
        });
        jPanel7.add(jTextFieldNom);

        jPanel9.add(jPanel7);
        jPanel9.add(filler6);
        jPanel9.add(filler9);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(93, 13, 110));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRENOM :");
        jPanel9.add(jLabel7);
        jPanel9.add(filler12);

        jTextFieldPrenoms.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextFieldPrenoms.setForeground(new java.awt.Color(93, 13, 110));
        jTextFieldPrenoms.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrenoms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 172, 113), 2));
        jTextFieldPrenoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomsActionPerformed(evt);
            }
        });
        jPanel9.add(jTextFieldPrenoms);

        jPanel5.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(93, 13, 110));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TEL :");
        jPanel13.add(jLabel8);
        jPanel13.add(filler13);

        jTextFieldTelephone.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextFieldTelephone.setForeground(new java.awt.Color(93, 13, 110));
        jTextFieldTelephone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTelephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 172, 113), 2));
        jTextFieldTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelephoneActionPerformed(evt);
            }
        });
        jPanel13.add(jTextFieldTelephone);

        jPanel12.add(jPanel13);
        jPanel12.add(filler7);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(93, 13, 110));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("E-MAIL :");
        jPanel12.add(jLabel9);
        jPanel12.add(filler14);

        jTextFieldMail.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jTextFieldMail.setForeground(new java.awt.Color(93, 13, 110));
        jTextFieldMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 172, 113), 2));
        jTextFieldMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMailActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldMail);

        jPanel5.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 1010, 660));

        jPanel8.setBackground(new java.awt.Color(15, 172, 113));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 172, 113), 3, true));

        jPanel11.setBackground(new java.awt.Color(15, 172, 113));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Acceuil.png"))); // NOI18N
        jPanel11.add(jLabel11);
        jPanel11.add(filler1);

        jButton2.setBackground(new java.awt.Color(200, 200, 200));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(93, 13, 110));
        jButton2.setText("Acceuil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2);

        jPanel8.add(jPanel11);
        jPanel8.add(filler5);

        jPanel10.setBackground(new java.awt.Color(15, 172, 113));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Virement.png"))); // NOI18N
        jPanel10.add(jLabel10);
        jPanel10.add(filler2);

        jButton1.setBackground(new java.awt.Color(200, 200, 200));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(93, 13, 110));
        jButton1.setText("VIREMENT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);

        jPanel8.add(jPanel10);
        jPanel8.add(filler15);

        jPanel15.setBackground(new java.awt.Color(15, 172, 113));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Arg1.png"))); // NOI18N
        jPanel15.add(jLabel13);
        jPanel15.add(filler4);

        jButton4.setBackground(new java.awt.Color(200, 200, 200));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(93, 13, 110));
        jButton4.setText("FAIRE_PRËT");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton4);

        jPanel8.add(jPanel15);
        jPanel8.add(filler16);

        jPanel14.setBackground(new java.awt.Color(15, 172, 113));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projet.Image/Arg2.png"))); // NOI18N
        jPanel14.add(jLabel12);
        jPanel14.add(filler3);

        jButton3.setBackground(new java.awt.Color(200, 200, 200));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(93, 13, 110));
        jButton3.setText("RENDRE_PRÊT");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton3);

        jPanel8.add(jPanel14);
        jPanel8.add(filler17);

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 100, 230, 660));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        
        //Récuperation du rang de la ligne selectionnée
        int numeroLigneSupprimer = jTableAffichageClient.getSelectedRow();
        
        //Récupération de la valeur de la colonne numeroCompte
        String valeurNumeroCompte = jTableAffichageClient.getValueAt(numeroLigneSupprimer,0).toString();
        
        CrudClient crud = new CrudClient();
        crud.supprimerClient(valeurNumeroCompte);
        
        // Effacer les textes sur les champs
        jTextFieldNom.setText("");
        jTextFieldPrenoms.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldMail.setText("");
        
        
        
        
        
        affichageInstantanee();
        
        JOptionPane.showMessageDialog(null,"Suppression du client reussie", "Information", JOptionPane.INFORMATION_MESSAGE );
               
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        
        CrudClient crud = new CrudClient();
        
        String nom = jTextFieldNom.getText();
        String prenoms = jTextFieldPrenoms.getText();
        String telephone = jTextFieldTelephone.getText();
        String mail = jTextFieldMail.getText();
        
        //Récupération de la valeur dans la colonne numeroClient
        int numeroLigne = jTableAffichageClient.getSelectedRow();
        
        String numeroClientObtenu = jTableAffichageClient.getValueAt(numeroLigne,0).toString();
        
        crud.modifierClient(nom, prenoms, telephone, mail, numeroClientObtenu);
        
        // Effacer les textes sur les champs
        jTextFieldNom.setText("");
        jTextFieldPrenoms.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldMail.setText("");
        
        
        affichageInstantanee();
        
        
        JOptionPane.showMessageDialog(null,"Modifcation du client reussie", "Information", JOptionPane.INFORMATION_MESSAGE );
               
    }//GEN-LAST:event_jButtonModifierActionPerformed
    //affichage après lancement de l'application
    private void affichageInstantanee(){
        
        CrudClient affichage = new CrudClient();
            //Récupération des données(sous fomre de liste) dans  la DonneesLiteClient à partir de la méthode affichageClient()
            List<DonneesListeClient> listeClients = affichage.affichageClient();
        
            //Récupération de la table jTableAffichageClient
            DefaultTableModel tableModel = (DefaultTableModel) jTableAffichageClient.getModel();
            
            //Efface toutes les lignes existantes dans la table
            tableModel.setRowCount(0);
        
            //Parcours de la liste des clients et ajouts dans la table
            for(DonneesListeClient parcours: listeClients){
            Object[] rowData = { parcours.getNumeroCompte(), parcours.getNom(), parcours.getPrenoms(), parcours.getTelephone(), parcours.getMail()};
            tableModel.addRow(rowData);
            }   
        
            //Mis à jour la table
            jTableAffichageClient.setModel(tableModel);
        
        
    }
    
    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        
        // DEBUT AJOUT CLIENT
        //Creation de l'objet ajoutClient de la classe Crud
        CrudClient ajoutClient = new CrudClient();
       
        
        //Conversion de l'objet JTextField en type String car la méthode ajoutClient attends des types String en arguments
        
        String nom = jTextFieldNom.getText();
        String prenoms = jTextFieldPrenoms.getText();
        String telephone = jTextFieldTelephone.getText();
        String mail = jTextFieldMail.getText();
        
        //FIN AJOUT CLIENT
        
        
        
        
        
        
        
        //DEBUT AFFICHAGE DE LA LISTE DES CLIENTS
        
        
        if(!jTextFieldNom.getText().isEmpty() && !jTextFieldPrenoms.getText().isEmpty() && !jTextFieldTelephone.getText().isEmpty() && !jTextFieldMail.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Ajout du client reussie", "Information", JOptionPane.INFORMATION_MESSAGE );
           
             ajoutClient.ajoutClient(nom, prenoms, telephone, mail);
        
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "ATTENTION", JOptionPane.ERROR_MESSAGE);
        }
        
        //FIN AFFICHAGE DE LA LISTE DES CLIENTS
        
        
        // Effacer les textes sur les champs
        jTextFieldNom.setText("");
        jTextFieldPrenoms.setText("");
        jTextFieldTelephone.setText("");
        jTextFieldMail.setText("");
        
        
        
        
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTextFieldMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMailActionPerformed

    private void jTextFieldTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelephoneActionPerformed

    private void jTextFieldPrenomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomsActionPerformed

    private void jTextFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
// Code pour changer de page////////////////////////////////////////////////////////////////////////////
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            new DesignVirement().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        new DesignFairePret().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       new DesignRendrePret().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTableAffichageClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAffichageClientMouseClicked
        // TODO add your handling code here:
        
        
        //1er METHODE
        
        /*
        DefaultTableModel model = (DefaultTableModel) jTableAffichageClient.getModel();
        
        //Récupération du rang de la ligne selection
        int ligneCliquee = jTableAffichageClient.getSelectedRow();
        
        JOptionPane.showMessageDialog(null, jTableAffichageClient.getValueAt(ligneCliquee, 0));
        
        //Affichage des valeurs de JTable sur les champs de saisies
        jTextFieldNom.setText(model.getValueAt(ligneCliquee,1).toString());
        jTextFieldPrenoms.setText(model.getValueAt(ligneCliquee,2).toString());
        jTextFieldTelephone.setText(model.getValueAt(ligneCliquee,3).toString());
        jTextFieldMail.setText(model.getValueAt(ligneCliquee,4).toString());
        
        */
        
        //2eme méthode
        
        //Récupération du rang de la ligne selection
        int ligneCliquee = jTableAffichageClient.getSelectedRow();
        
        
        jTextFieldNom.setText(jTableAffichageClient.getValueAt(ligneCliquee, 1).toString());
        jTextFieldPrenoms.setText(jTableAffichageClient.getValueAt(ligneCliquee, 2).toString());
        jTextFieldTelephone.setText(jTableAffichageClient.getValueAt(ligneCliquee, 3).toString());
        jTextFieldMail.setText(jTableAffichageClient.getValueAt(ligneCliquee, 4).toString());
        
        
    }//GEN-LAST:event_jTableAffichageClientMouseClicked
    
   
    
 
    private void jTextFieldRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechercherActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jTextFieldRechercherActionPerformed
    
    
   
    private void jTextFieldRechercherInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldRechercherInputMethodTextChanged
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_jTextFieldRechercherInputMethodTextChanged

    
   
    private void recherche(String requeteRecherche){
        
        DefaultTableModel model = (DefaultTableModel) jTableAffichageClient.getModel();
        TableRowSorter<DefaultTableModel> table = new TableRowSorter<>(model);
        jTableAffichageClient.setRowSorter(table);
        
        
        table.setRowFilter(RowFilter.regexFilter(requeteRecherche));
        
        
    }
    
    
 
    private void jTextFieldRechercherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercherKeyPressed
        // TODO add your handling code here:     
        
    }//GEN-LAST:event_jTextFieldRechercherKeyPressed

    private void jTextFieldRechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRechercherKeyReleased
        // TODO add your handling code here:
        String chaine = jTextFieldRechercher.getText();
        recherche(chaine);
        
        
        if(jTextFieldRechercher.getText().isEmpty()){
             affichageInstantanee();
        }
        
    }//GEN-LAST:event_jTextFieldRechercherKeyReleased




// Code pour changer de page////////////////////////////////////////////////////////////////////////////
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRechercher;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAffichageClient;
    private javax.swing.JTextField jTextFieldMail;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenoms;
    private javax.swing.JTextField jTextFieldRechercher;
    private javax.swing.JTextField jTextFieldTelephone;
    // End of variables declaration//GEN-END:variables
}


